### ISSUE TITLE
deprecation notice

### ISSUE THREAD

**Issue by faust64** [PeerioTechnologies/peerio-linux-repository#9]
Might want to add some warning regarding our client being deprecated.
Not being sure yet how we would distribute it, we could at least mention https://github.com/PeerioTechnologies/peerio-desktop/releases -- or wait for @dchest , currently investigating that question.

**Comment by faust64** [comment]
Forgot to mention our issue in my commit .... PeerioTechnologies/peerio-linux-repository@de083d29840c91fcd3f0b26c60f865a35fef7536
I'll assume that's enough? Unless @flohdot thinks otherwise? I'll push that change later today or tomorrow.

**Comment by faust64** [comment]
now shipping - PeerioTechnologies/peerio-websites@26ad6b904fa9b01d480eaf33e3c8109e5a2460aa

**Comment by flohdot** [comment]
👍
